import type { DocumentSummary } from '@/types/ai';

/**
 * Convert a DocumentSummary into a well-formatted GitHub Flavored Markdown document.
 */
export function summaryToMarkdown(summary: DocumentSummary): string {
  const parts: string[] = [];

  parts.push(`# ${summary.title}`);
  parts.push('');

  parts.push('## Executive Overview');
  parts.push(summary.overview);
  parts.push('');

  if (summary.keyPoints && summary.keyPoints.length > 0) {
    parts.push('## Key Takeaways');
    for (const point of summary.keyPoints) {
      parts.push(`* ${point}`);
    }
    parts.push('');
  }

  if (summary.sections && summary.sections.length > 0) {
    parts.push('## Detailed Sections');
    for (const section of summary.sections) {
      const pageInfo = section.sourcePages && section.sourcePages.length > 0
        ? ` *(Pages: ${section.sourcePages.join(', ')})*`
        : '';
      parts.push(`### ${section.heading}${pageInfo}`);
      parts.push(section.content);
      parts.push('');

      if (section.keyFindings && section.keyFindings.length > 0) {
        parts.push('**Key Findings:**');
        for (const finding of section.keyFindings) {
          parts.push(`- ${finding}`);
        }
        parts.push('');
      }
    }
  }

  if (summary.sourceReferences && summary.sourceReferences.length > 0) {
    parts.push('## Source Provenance');
    for (const ref of summary.sourceReferences) {
      parts.push(`* **Page ${ref.pageNumber}** (${ref.chunkId}): ${ref.relevance}`);
    }
    parts.push('');
  }

  parts.push('---');
  parts.push(`*Generated by Document Summary Assistant • Model: ${summary.metadata.model} • ${new Date(summary.metadata.generatedAt).toLocaleDateString()}*`);

  return parts.join('\n');
}
